/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class paymentform extends javax.swing.JInternalFrame {

    /**
     * Creates new form paymentform
     */
    public paymentform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ordernametxt = new javax.swing.JTextField();
        pricelandtxt = new javax.swing.JTextField();
        areacombobox = new javax.swing.JComboBox<>();
        imgicon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t36radiobtn = new javax.swing.JRadioButton();
        t45radiobtn = new javax.swing.JRadioButton();
        t54radiobtn = new javax.swing.JRadioButton();
        buildingpricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        largelandtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        availablelandtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        DPtxt = new javax.swing.JTextField();
        instalmentamount = new javax.swing.JTextField();
        ppntxt = new javax.swing.JTextField();
        instalmentmonthtxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        agreementcbx = new javax.swing.JCheckBox();
        processbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setTitle("MENU PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah (Rp)");

        jLabel3.setText("Area");

        pricelandtxt.setEditable(false);
        pricelandtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        areacombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "EUROPEAN", "JAPANESE", "AMERICAN" }));
        areacombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areacomboboxActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Bangunan (Rp)");

        jLabel6.setText("Tipe Rumah");

        t36radiobtn.setText("Tipe - 36");
        t36radiobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        t36radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36radiobtnActionPerformed(evt);
            }
        });

        t45radiobtn.setText("Tipe - 45");
        t45radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45radiobtnActionPerformed(evt);
            }
        });

        t54radiobtn.setText("Tipe - 54");
        t54radiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54radiobtnActionPerformed(evt);
            }
        });

        buildingpricetxt.setEditable(false);
        buildingpricetxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Luas Tanah Asli (m)");

        largelandtxt.setEditable(false);
        largelandtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas Tanah Tersedia (m)");

        availablelandtxt.setEditable(false);
        availablelandtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Harga (Rp)");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPN (10%)");

        jLabel13.setText("Cicilan/Bln");

        pricetxt.setEditable(false);
        pricetxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentamount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppntxt.setEditable(false);
        ppntxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentmonthtxt.setEditable(false);
        instalmentmonthtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Bulan");

        agreementcbx.setText("Setuju");
        agreementcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementcbxActionPerformed(evt);
            }
        });

        processbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/refresh-16x16.png"))); // NOI18N
        processbtn.setText("PROSES");
        processbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processbtnActionPerformed(evt);
            }
        });

        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/save-16x16.png"))); // NOI18N
        savebtn.setText("SIMPAN");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/close-16x16.png"))); // NOI18N
        deletebtn.setText("HAPUS");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/back-16x16.png"))); // NOI18N
        backbtn.setText("KEMBALI");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(imgicon, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ordernametxt)
                                .addComponent(pricelandtxt)
                                .addComponent(areacombobox, 0, 140, Short.MAX_VALUE))))
                    .addComponent(backbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(t36radiobtn)
                                .addComponent(t45radiobtn)
                                .addComponent(t54radiobtn)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buildingpricetxt)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(largelandtxt)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availablelandtxt)
                            .addComponent(pricetxt)
                            .addComponent(DPtxt)
                            .addComponent(instalmentamount)
                            .addComponent(ppntxt)
                            .addComponent(instalmentmonthtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(agreementcbx)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(processbtn)
                        .addGap(18, 18, 18)
                        .addComponent(savebtn)
                        .addGap(18, 18, 18)
                        .addComponent(deletebtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buildingpricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(largelandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(availablelandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ordernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pricelandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(areacombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t36radiobtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgicon)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t45radiobtn)
                                .addGap(18, 18, 18)
                                .addComponent(t54radiobtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(instalmentamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ppntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(instalmentmonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agreementcbx))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processbtn)
                    .addComponent(savebtn)
                    .addComponent(deletebtn)
                    .addComponent(backbtn))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areacomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areacomboboxActionPerformed
        switch(areacombobox.getSelectedIndex()){
            case 0:
                pricelandtxt.setText("");
                buildingpricetxt.setText("");
                t36radiobtn.setSelected(false);
                t45radiobtn.setSelected(false);
                t54radiobtn.setSelected(false);
                largelandtxt.setText("");
                availablelandtxt.setText("");
                pricetxt.setText("");
                DPtxt.setText("");
                instalmentamount.setText("");
                instalmentmonthtxt.setText("");
                ppntxt.setText("");
                agreementcbx.setSelected(false);
                
                imgicon.setIcon(null);
                break;
                
            case 1:
                pricelandtxt.setText("500000000");
                buildingpricetxt.setText("900000000");
                t36radiobtn.setSelected(false);
                t45radiobtn.setSelected(false);
                t54radiobtn.setSelected(false);
                largelandtxt.setText("");
                availablelandtxt.setText("");
                pricetxt.setText("");
                DPtxt.setText("");
                instalmentamount.setText("");
                instalmentmonthtxt.setText("");
                ppntxt.setText("");
                agreementcbx.setSelected(false);
                
                imgicon.setIcon(new ImageIcon("src/aplikasipenjualan/european.png"));
                break;
                
            case 2:
                pricelandtxt.setText("600000000");
                buildingpricetxt.setText("1200000000");
                t36radiobtn.setSelected(false);
                t45radiobtn.setSelected(false);
                t54radiobtn.setSelected(false);
                largelandtxt.setText("");
                availablelandtxt.setText("");
                pricetxt.setText("");
                DPtxt.setText("");
                instalmentamount.setText("");
                instalmentmonthtxt.setText("");
                ppntxt.setText("");
                agreementcbx.setSelected(false);
                
                imgicon.setIcon(new ImageIcon("src/aplikasipenjualan/japanese.png"));
                break;
                
            default:
                pricelandtxt.setText("700000000");
                buildingpricetxt.setText("1500000000");
                t36radiobtn.setSelected(false);
                t45radiobtn.setSelected(false);
                t54radiobtn.setSelected(false);
                largelandtxt.setText("");
                availablelandtxt.setText("");
                pricetxt.setText("");
                DPtxt.setText("");
                instalmentamount.setText("");
                instalmentmonthtxt.setText("");
                ppntxt.setText("");
                agreementcbx.setSelected(false);
                
                imgicon.setIcon(new ImageIcon("src/aplikasipenjualan/american.png"));
                break;
        }
    }//GEN-LAST:event_areacomboboxActionPerformed

    private void t36radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36radiobtnActionPerformed
       if(areacombobox.getSelectedIndex() == 0) {
           JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu!");
           t36radiobtn.setSelected(false);
           t45radiobtn.setSelected(false);
           t54radiobtn.setSelected(false);
       }else {
           largelandtxt.setText("90");
           availablelandtxt.setText("54");
           long landprice = Long.parseLong(pricelandtxt.getText()),
                   buildingprice = Long.parseLong(buildingpricetxt.getText()),
                   availableland = Long.parseLong(availablelandtxt.getText()),
                   totalprice;
           totalprice = (availableland * landprice) + buildingprice;
           pricetxt.setText(("" + totalprice));
           
           instalmentamount.setText("");
           DPtxt.setText("");
           ppntxt.setText("");
           instalmentmonthtxt.setText("");
       }
    }//GEN-LAST:event_t36radiobtnActionPerformed

    private void t45radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45radiobtnActionPerformed
        if(areacombobox.getSelectedIndex() == 0) {
           JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu!");
           t36radiobtn.setSelected(false);
           t45radiobtn.setSelected(false);
           t54radiobtn.setSelected(false);
       }else {
           largelandtxt.setText("120");
           availablelandtxt.setText("75");
           long landprice = Long.parseLong(pricelandtxt.getText()),
                   buildingprice = Long.parseLong(buildingpricetxt.getText()),
                   availableland = Long.parseLong(availablelandtxt.getText()),
                   totalprice;
           totalprice = (availableland * landprice) + buildingprice;
           pricetxt.setText(("" + totalprice));
           
           instalmentamount.setText("");
           DPtxt.setText("");
           ppntxt.setText("");
           instalmentmonthtxt.setText("");
       }

    }//GEN-LAST:event_t45radiobtnActionPerformed

    private void t54radiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54radiobtnActionPerformed
        if(areacombobox.getSelectedIndex() == 0) {
           JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu!");
           t36radiobtn.setSelected(false);
           t45radiobtn.setSelected(false);
           t54radiobtn.setSelected(false);
       }else {
           largelandtxt.setText("140");
           availablelandtxt.setText("86");
           long landprice = Long.parseLong(pricelandtxt.getText()),
                   buildingprice = Long.parseLong(buildingpricetxt.getText()),
                   availableland = Long.parseLong(availablelandtxt.getText()),
                   totalprice;
           totalprice = (availableland * landprice) + buildingprice;
           pricetxt.setText(("" + totalprice));
           
           instalmentamount.setText("");
           DPtxt.setText("");
           ppntxt.setText("");
           instalmentmonthtxt.setText("");
       }

    }//GEN-LAST:event_t54radiobtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        ordernametxt.setText("");
        pricelandtxt.setText("");
        buildingpricetxt.setText("");
        largelandtxt.setText("");
        availablelandtxt.setText("");
        pricetxt.setText("");
        DPtxt.setText("");
        instalmentamount.setText("");
        instalmentmonthtxt.setText("");
        ppntxt.setText("");
        areacombobox.setSelectedIndex(0);
        t36radiobtn.setSelected(false);
        t45radiobtn.setSelected(false);
        t54radiobtn.setSelected(false);
        agreementcbx.setSelected(false);
    }//GEN-LAST:event_deletebtnActionPerformed

    private void processbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processbtnActionPerformed
        if(pricetxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilihan Belum Lengkap!");
        } else if(DPtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP Harus Diisi!");
        } else if(instalmentamount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Lama Cicilan Yang Diinginkan!");
        } else {
            long landprice = Long.parseLong(pricelandtxt.getText()),
                   buildingprice = Long.parseLong(buildingpricetxt.getText()),
                   availableland = Long.parseLong(availablelandtxt.getText()),
                   dp = Long.parseLong(DPtxt.getText()),
                   installmentamount = Long.parseLong(instalmentamount.getText()),
                   totalprice, ppn, installmentpermonth;
            totalprice = (availableland * landprice) + buildingprice;
            ppn = totalprice * 10 / 100;
            installmentpermonth = (totalprice + ppn) / installmentamount;
            ppntxt.setText("" + ppn);
            instalmentmonthtxt.setText("" + installmentpermonth);
        }
    }//GEN-LAST:event_processbtnActionPerformed

    private void agreementcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementcbxActionPerformed
        if(ordernametxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Pemesan Harus Diisi Terlebih Dahulu!");
            agreementcbx.setSelected(false);
        } else if (ppntxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan Tombol Proses Terlebih Dahulu!");
            agreementcbx.setSelected(false);
        } else if (agreementcbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Pembeli Menyetujui");
            agreementcbx.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pembeli Belum Menyetujui");
            agreementcbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementcbxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        optionmenu Optionmenu = new optionmenu();
        Optionmenu.setVisible(true);
        this.getDesktopPane().add(Optionmenu);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if(agreementcbx.isSelected() == false){
            JOptionPane.showMessageDialog(null, 
                    "Klik Centang Terlebih Dahulu Untuk Simpan Data!", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String typeHouse;
            if (t36radiobtn.isSelected()){
                typeHouse = "TIPE 36";
            } else if (t45radiobtn.isSelected()){
                typeHouse = "TIPE 45";
            } else {
                typeHouse = "TIPE 54";
            }
            
            
            try{
                String sql = "INSERT INTO rumah (name, area, tipe, luas, harga, jmlh_cicilan, cicilan_bln) VALUES ('"
                        + ordernametxt.getText() + "','"
                        + areacombobox.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + largelandtxt.getText() + "','"
                        + pricetxt.getText() + "','"
                        + instalmentamount.getText() + "','"
                        + instalmentmonthtxt.getText() + "')";
                Connection conn = (Connection)Connectiondb.connectDatabase();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                
            } catch (SQLException ex) {
                Logger.getLogger(paymentform.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            optionmenu Optionmenu = new optionmenu();
            Optionmenu.setVisible(true);
            this.getDesktopPane().add(Optionmenu);
            this.dispose();
            
        }
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPtxt;
    private javax.swing.JCheckBox agreementcbx;
    private javax.swing.JComboBox<String> areacombobox;
    private javax.swing.JTextField availablelandtxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField buildingpricetxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel imgicon;
    private javax.swing.JTextField instalmentamount;
    private javax.swing.JTextField instalmentmonthtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largelandtxt;
    private javax.swing.JTextField ordernametxt;
    private javax.swing.JTextField ppntxt;
    private javax.swing.JTextField pricelandtxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JButton processbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JRadioButton t36radiobtn;
    private javax.swing.JRadioButton t45radiobtn;
    private javax.swing.JRadioButton t54radiobtn;
    // End of variables declaration//GEN-END:variables
}
